bogle-bogle/thepet-frontend

src/App.js, src/components/login/RedirectUrl.jsx, src/pages/CartPage.jsx
=> feat(cart) : 장바구니 구현 시작

src/App.css, src/App.js, src/components/cart/CartCard.jsx, src/components/cart/CartContainer.jsx, src/components/cart/CartInfo.jsx, src/components/ordersheet/OrderMember.jsx, src/components/ordersheet/OrderMember.style.js, src/components/ordersheet/OrderProducts.jsx, src/components/ordersheet/OrderProducts.style.js, src/pages/Main.jsx, src/pages/OrderSheetPage.jsx
- #17
- 주문자 멤버 정보 불러오기
- 장바구니 cart+prodcut 정보 합쳐서 새로운 객체로 만들어서 주문서로 전달하기
=> 주문서 페이지 구현

src/App.js, src/components/cart/CartHeader.jsx, src/components/cart/CartHeader.style.js, src/components/cart/CartInfo.jsx, src/components/cart/CartInfo.style.js, src/components/ordercomplete/CompleteMessage.jsx, src/components/ordercomplete/CompleteMessage.style.js, src/components/ordercomplete/OrderCompleteHeader.jsx, src/components/ordercomplete/OrderCompleteHeader.style.js, src/components/ordercomplete/OrderInfo.jsx, src/components/ordercomplete/OrderInfo.style.js, src/components/ordersheet/OrderProducts.jsx, src/components/ordersheet/OrderProducts.style.js, src/components/ordersheet/OrderSheetHeader.jsx, src/components/ordersheet/OrderSheetHeader.style.js, src/pages/CartPage.jsx, src/pages/OrderComplete.jsx, src/pages/OrderSheetPage.jsx
=> 주문서, 주문 완료 페이지 화면 구현

src/setupProxy.js
=> fix: url 중복 제거

src/App.js, src/components/header/Header2.jsx, src/components/header/Header2.style.js, src/components/mypage/MyPageContainer.jsx, src/components/playground/PlayGroundContainer.jsx, src/pages/MyPage.jsx, src/pages/PlayGround.jsx
=> 장바구니 버튼 추가

.github/issue-branch.yml, .github/workflows/create_branch.yml, .github/workflows/create_jira_issue.yml
=> github actions 설정

src/components/header/Header2.jsx, src/components/header/Header2.style.js, src/feature/member/member.js
=> feat(logout) : 로그아웃 구현

src/api.js, src/components/header/Header2.jsx, src/components/login/KakaoLoginButton.jsx, src/setupProxy.js
url 연결 환경변수 사용으로 수정(.env)
- 
-
=> fix: url 연결 수정

src/pages/MainLayout.jsx
=> fix: 헤더 수정

src/components/club/AddPetContainer.jsx, src/components/custom/CustomResult.jsx, src/components/header/Header2.jsx, src/components/suggestion/ImageUploadComponent.jsx, src/components/suggestion/InputPetInfo.jsx, src/components/suggestion/SuggestionContainer.jsx, src/components/suggestion/SuggestionOuterContainer.jsx, src/components/suggestion/image-upload-component.style.js, src/components/suggestion/suggestion.style.js, src/pages/Suggestion.jsx
=> suggestion 수정 완료

src/components/suggestion/ImageUploadComponent.jsx, src/components/suggestion/InputPetInfo.jsx, src/components/suggestion/SuggestionOuterContainer.jsx
=> fix(suggestion): api 호출 관련 수정

src/components/club/AddPetContainer.jsx, src/components/mypage/MyPageContainer.jsx, src/components/suggestion/InputPetInfo.jsx
=> fix: 반려동물 등록 페이지 수정

src/App.js, src/components/club/AddPetContainer.jsx, src/components/header/Header.jsx, src/components/suggestion/SuggestionOuterContainer.jsx
=> fix(addpet): 반려동물 등록 수정

package-lock.json, package.json, src/App.css, src/App.js, src/components/footer/footer.style.js, src/components/header/Header2.jsx, src/components/thepetbox/MonthlyBox.jsx, src/components/thepetbox/ThePetBoxContainer.jsx, src/components/thepetbox/thepetbox.style.js, src/pages/MainLayout.jsx, src/pages/ThePetBox.jsx, src/styles/GlobalStyle.js
=> feat(sub): 구독 페이지 디자인 수정, footer 하단 고정

src/components/product/index.style.jsx
=> feat(product): product card style 수정

public/index.html, src/RouteChangeTracker.js
=> feat(GA4): GA4 테스트

src/App.js, src/components/ordersheet/OrderProducts.jsx, src/components/toss/TossRedirect.jsx, src/pages/OrderComplete.jsx
=> 토스 결제 승인 요청 redirect

src/RouteChangeTracker.js, src/components/ordercomplete/CompleteMessage.jsx, src/components/ordercomplete/OrderInfo.jsx, src/components/ordersheet/OrderMember.jsx, src/components/ordersheet/OrderProducts.jsx, src/components/toss/TossRedirect.jsx, src/pages/OrderComplete.jsx
=> 주문 완료 페이지 띄우기 수정

src/components/cart/CartCard.jsx, src/components/cart/CartContainer.jsx, src/components/cart/CartInfo.jsx
=> 장바구니 개수 오류 수정

src/components/ordercomplete/OrderInfo.jsx
=> feat(complete) : 장바구니 오류 수정 main으로

src/components/heendycar/HeendycarContainer.jsx
=> fix: 배포용 긴급 수정

src/components/global/NoDataBox.jsx, src/components/global/nodatabox.style.js, src/components/mypage/MyOrderContainer.jsx, src/components/mypage/MyReservationContainer.jsx, src/components/mypage/MySubscriptionContainer.jsx, src/components/suggestion/SuggestionOuterContainer.jsx, src/components/suggestion/suggestion.style.js
=> feat: NoDataBox 컴포넌트화

src/api.js, src/feature/member/member.js
=> fix: redux 관련 수정

src/components/heendycar/HeendyCarReservation.jsx, src/components/product/ProductDetail.jsx
=> fix(swal): import swal

src/components/global/showRequiredLoginSwal.jsx
=> feat(login): login swal 닫기 수정

src/components/cart/CartCard.jsx, src/components/cart/CartContainer.jsx, src/components/cart/CartInfo.jsx, src/components/mbti/MbtiGame.jsx, src/components/mbti/mbti.style.js, src/components/product/NewProductList.jsx, src/components/product/Review.jsx, src/components/product/index.style.jsx, src/components/recommendation/ProductRecommendation.jsx, src/components/suggestion/InputPetInfo.jsx
=> fix(shop, mbti): shop 상품 목록 알러지 경고

src/components/product/NewProductList.jsx
=> feat(product): cart 수정

.bashrc
=> feat(memory): 메모리 증가

.bashrc, src/components/product/NewProductList.jsx
=> add memory

src/components/product/NewProductList.jsx
=> fix(product): delete console.log

src/components/global/DrawingHeendySwal.jsx, src/components/global/SadHeendySwal.jsx, src/components/mypage/MyReservationContainer.jsx, src/components/mypage/mypage.style.jsx, src/components/ordersheet/OrderProducts.jsx, src/components/ordersheet/OrderProducts.style.js, src/components/ordersheet/OrderSheetHeader.jsx, src/components/product/ProductDetail.jsx, src/components/product/ProductSummaryContainer.jsx, src/components/toss/TossCardRegisterRedirect.jsx, src/pages/OrderSheetPage.jsx
=> 정기배송 카드 확인

src/App.js, src/components/product/NewProductList.jsx, src/components/recommendation/index.style.jsx
=> feat(shop): 펫 정보 바꾸기, 추천 상품 컴포넌트 추가

src/components/hyundaicard/card.style.js, src/components/product/NewProductList.jsx, src/components/product/index.style.jsx, src/components/recommendation/ProductRecommendation.jsx, src/components/recommendation/index.style.jsx
=> feat(shop): 전체적인 구성 수정

src/App.js, src/components/hyundaicard/card.style.js, src/components/product/NewProductList.jsx, src/components/product/index.style.jsx, src/components/recommendation/ProductRecommendation.jsx, src/components/recommendation/index.style.jsx
=> shop 페이지 수정

src/App.js, src/components/login/RedirectUrl2.jsx
=> feat(login): login 알고리즘 백엔드 이동

package.json, src/components/header/Header2.jsx, src/components/login/RedirectUrl2.jsx, src/components/main/landing.style.js
=> fix(login): test

src/App.js, src/index.js, src/pages/MainLayout.jsx
=> fix(login): 코드 수정

src/App.js, src/components/login/RedirectUrl2.jsx
=> fix(login): redirect 수정

src/pages/Landing.jsx
=> fix(test): test

src/App.js
=> feat(login): test2

src/App.js, src/index.js
=> fix(App): lazy 코드로 수정

src/App.js, src/index.js
=> lazy 코드로 수정

src/components/login/RedirectUrl2.jsx, src/pages/Landing.jsx
=> fix(login): console.log 삭제

src/App.js, src/components/login/RedirectUrl.jsx, src/components/suggestion/InputPetInfo.jsx, src/pages/HyundaiCard.jsx
=> feat(image cropper): image cropper 코드 수정

src/commonCode.js, src/components/heendycar/HeendyCarReservation.jsx, src/components/mbti/MbtiGame.jsx, src/components/mbti/mbti.style.js, src/components/ordersheet/OrderProducts.jsx, src/components/recommendation/ProductRecommendation.jsx, src/components/toss/TossRedirect.jsx, src/ga/index.jsx, src/utils/event_log.js
=> fix(mbti): mbit 페이지 전체 수정

.github/workflows/main.yml
=> fix(yml): .env 에 변수 추가

src/components/mbti/mbti.style.js
=> fix(mbti): 스타일 수정

.github/workflows/main.yml, src/components/mbti/mbti.style.js
=> mbti 스타일 수정

src/components/mbti/mbti.style.js
=> feat(mbti): mbti 스타일 수정

src/components/mypage/MySubscriptionContainer.jsx, src/components/ordersheet/OrderProducts.jsx, src/components/ordersheet/OrderSheetHeader.jsx, src/components/product/ProductDetail.jsx, src/components/thepetbox/ThePetBoxContainer.jsx
=> 주문서에 카드 붙이고 월간구독 주문서로 이어붙이기

src/components/mypage/MyReservationContainer.jsx
=> fix(mypage) : 흰디카 취소하기 수정

src/pages/HyundaiCard.jsx
=> feat: 현대백화점 카드 링크 연결

src/components/main/LandingContainer.jsx
=> feat: 가입하기 임시 버튼 생성

src/components/mypage/mypage.style.jsx
=> feat: 임시 - 마이페이지 수정

src/components/club/AddPetContainer.jsx, src/components/custom/CustomResult.jsx, src/components/custom/custom-result.style.js, src/components/mbti/MbtiGame.jsx, src/components/product/NewProductList.jsx, src/components/product/ProductDetail.jsx, src/components/product/index.style.jsx, src/components/scroll/ScrollToTop.jsx, src/components/suggestion/InputPetInfo.jsx, src/components/suggestion/SuggestionOuterContainer.jsx, src/feature/member/member.js, src/index.js
=> fix(front): 전체적인 스타일 및 기능 수정

src/components/product/ProductDetail.jsx
=> fix(product)detail): useHistory() 삭제

src/components/product/ProductDetail.jsx, src/pages/HyundaiCard.jsx
=> 불필요한 코드 삭제

src/components/main/landing.style.js, src/components/product/ProductDetail.jsx
=> style: 디자인 변경

src/components/mypage/MySubscriptionContainer.jsx, src/components/mypage/mypage.style.jsx, src/components/ordersheet/OrderProducts.jsx
=> fix: 카드등록 처음으로 돌아가기

public/index.html, src/App.css, src/App.js, src/components/login/RedirectUrl.jsx, src/components/mbti/MbtiGame.jsx, src/pages/MainLayout.jsx
=> fix(footer): footer 위치 수정

public/index.html, src/App.css, src/App.js, src/components/login/RedirectUrl.jsx, src/components/mbti/MbtiGame.jsx, src/components/product/ProductDetail.jsx, src/pages/MainLayout.jsx
=> footer 위치 수정

src/App.js
=> fix(footer): footer 태그 위치 수정

src/components/footer/footer.style.js, src/components/mypage/mypage.style.jsx, src/components/ordersheet/OrderProducts.jsx, src/components/ordersheet/OrderProducts.style.js
=> style : css

src/components/floating/Floating.jsx, src/components/floating/floating.style.js, src/components/mbti/MbtiGame.jsx, src/pages/MainLayout.jsx
=> fix(floating): floating css 수정

src/components/floating/Floating.jsx
=> fix(floating): navigate 추가

src/components/custom/CustomResult.jsx, src/components/custom/custom-result.style.js
=> fix(ai): 100퍼센트일때 카드 수정

src/components/footer/footer.style.js
=> fix(footer): footer style 수정

src/components/thepetbox/ThePetBoxContainer.jsx
=> fix: 슬라이더 및 더펫박스 위치 수정

src/components/club/AddPetContainer.jsx, src/feature/member/member.js
=> fix(addpet): pet 추가 수정

src/components/hyundaicard/card.style.js, src/pages/HyundaiCard.jsx
=> feat: 현백 카드 모달 수정

src/components/main/landing.style.js, src/components/mypage/MySubscriptionContainer.jsx, src/components/ordersheet/OrderProducts.jsx, src/pages/HyundaiCard.jsx
=> fix css 및 할인금액 변경
